#13 - Write the jwt and password encrypt
ImmortalIdiot/RUTLead-Backend pull request #17
Opened 2024-04-17 19:19 UTC by Andreymlc

Write a jwt and register with authorization

2024-04-19 21:43 UTC, NN171 requested changes
Check the existence of empty line in every file

2024-04-19 21:43 UTC, NN171 commented on api/Controllers/AccountController.cs
> +                        return StatusCode(500, roleResult.Errors);
Are u sure, that u need to return the 500 code, but not the 400 code?

2024-04-19 21:43 UTC, NN171 commented on api/Controllers/AccountController.cs
> +                    return StatusCode(500, createUser.Errors);
The same question about 500 code

2024-04-19 21:43 UTC, NN171 commented on api/Controllers/AccountController.cs
> +                return StatusCode(500, e.Message);
The same question about 500 code

2024-04-19 21:49 UTC, NN171 commented on api/Program.cs
> +    options.DefaultSignInScheme =
What are this syntax means?

2024-04-19 21:49 UTC, NN171 commented on api/Controllers/AccountController.cs
> +                return StatusCode(500, e.Message);
Are u sure, that u need to return the 500 code(internal server error), instead 400 code(bad request)?

2024-04-20 08:29 UTC, jacksever commented on .gitignore
> +Migrations/
А разве миграции мы не передаем в Git? Что если я скачаю проект, сделаю миграцию и запушу без неё? Как другие разработчики должны мигрировать у себя базу и сущности без самой миграции? Хммм

2024-04-20 08:30 UTC, jacksever commented on api/Controllers/AccountController.cs
> +        private readonly SignInManager<AppUser> _signManager;
`UserManager` и `SignInManager `- это интерфейсы?

2024-04-20 08:31 UTC, jacksever commented on api/Controllers/AccountController.cs
> +
```suggestion
```

2024-04-20 08:31 UTC, jacksever commented on api/Controllers/AccountController.cs
> +
```suggestion
            if(!ModelState.IsValid) {
                return BadRequest(ModelState);
            }
            
```

Так более понятно будет)

2024-04-20 08:33 UTC, jacksever commented on api/Controllers/AccountController.cs
> +            var user = await _userManager.Users.FirstOrDefaultAsync(x => x.UserName == loginDto.StudentId.ToString());
UserName == StudentId?

Корректная проверка?

2024-04-20 08:34 UTC, jacksever commented on api/Controllers/AccountController.cs
> +            if(user == null) return Unauthorized("Неверный номер студенческого билета!");
Может `NotFound` возвращать, а не `Unauthorized`? Вы же никого ещё не авторизовывали

2024-04-20 08:35 UTC, jacksever commented on api/Controllers/AccountController.cs
> +            if(user == null) return Unauthorized("Неверный номер студенческого билета!");
```suggestion
            if (user == null) return Unauthorized("Неверный номер студенческого билета!");
```

2024-04-20 08:35 UTC, jacksever commented on api/Controllers/AccountController.cs
> +            if(!result.Succeeded) return Unauthorized("Неверное имя пользователя или пароль!");
```suggestion
            if (!result.Succeeded) return Unauthorized("Неверное имя пользователя или пароль!");
```

2024-04-20 08:35 UTC, jacksever commented on api/Controllers/AccountController.cs
> +                if(createUser.Succeeded)
```suggestion
                if (createUser.Succeeded)
```

2024-04-20 08:36 UTC, jacksever commented on api/Controllers/AccountController.cs
> +            }catch (Exception e)
```suggestion
            } catch (Exception e)
```

2024-04-20 08:36 UTC, jacksever commented on api/Controllers/AccountController.cs
> +                    return StatusCode(500, createUser.Errors);
А чего везде 500 ошибки-то возвращаются? Кажется, что мы вовсе не возвращаем 500 ошибку самостоятельно. Сервер её сам выкидывает, когда нужно

2024-04-20 08:37 UTC, jacksever commented on api/Dto/Account/LoginDto.cs
> +        public required string Password { get; set; }
```suggestion
        [Required]
        public required int StudentId { get; set; }
        
        [Required]
        public required string Password { get; set; }
```

2024-04-20 08:37 UTC, jacksever commented on api/Dto/Account/NewUserDto.cs
> +}
```suggestion

}
```

2024-04-20 08:38 UTC, jacksever commented on api/Dto/Account/NewUserDto.cs
> +}
```suggestion
}

```

В конце файла пустая строка обязательная для Git

2024-04-20 08:38 UTC, jacksever commented on api/Dto/Account/RegisterDto.cs
> +}
Пустая строка в конце файла

2024-04-20 08:38 UTC, jacksever commented on api/Interfaces/ITokenService.cs
> +}
Пустая строка в конце файла

2024-04-20 08:38 UTC, jacksever commented on api/Models/AppUser.cs
> +}
Пустая строка в конце файла

2024-04-20 08:39 UTC, jacksever commented on api/Models/AppUser.cs
> +namespace api.Models{
```suggestion
namespace api.Models {
```

2024-04-20 08:39 UTC, jacksever commented on api/Models/AppUser.cs
> +namespace api.Models{
Отформатируй код

2024-04-20 08:40 UTC, jacksever commented on api/Service/TokenService.cs
> +    public TokenService(IConfiguration config){
```suggestion
    private readonly SymmetricSecurityKey _key;
    
    public TokenService(IConfiguration config){
```

2024-04-20 08:40 UTC, jacksever commented on api/Service/TokenService.cs
> +        else{
```suggestion
        else {
```

2024-04-20 08:40 UTC, jacksever commented on api/Service/TokenService.cs
> +        if (!string.IsNullOrEmpty(secretKey)){
```suggestion
        if (!string.IsNullOrEmpty(secretKey)) {
```

2024-04-20 08:40 UTC, jacksever commented on api/Service/TokenService.cs
> +
```suggestion
```

2024-04-20 08:41 UTC, jacksever commented on api/Service/TokenService.cs
> +
```suggestion
```

2024-04-20 08:41 UTC, jacksever commented on api/Service/TokenService.cs
> +            Expires = DateTime.Now.AddDays(7),
That seems like quite a lot

2024-04-20 08:42 UTC, jacksever commented on api/Service/TokenService.cs
> +}
Пустая строка в конце файла

2024-04-20 08:42 UTC, jacksever commented on api/Service/TokenService.cs
> +        var token = tokenHandler.CreateToken(tokenDescriptor);
Всегда ли токен 100% создается? Не нужно ли обрабатывать ситуации, когда не вышло его сгенерировать?

2024-04-20 08:43 UTC, jacksever commented on api/appsettings.json
> +    "SecretKey": "9c56bbb2442aa20f7d48ce5ba13b75c38000266334fb008387322a8a8ff24944",
Оууу) Секреты в открытом доступе в Git? :))))

2024-04-20 14:41 UTC, Andreymlc commented on api/appsettings.json
> +    "SecretKey": "9c56bbb2442aa20f7d48ce5ba13b75c38000266334fb008387322a8a8ff24944",
Правильно будет использовать переменные окружения?

2024-04-20 15:43 UTC, Andreymlc commented on api/Controllers/AccountController.cs
> +        private readonly SignInManager<AppUser> _signManager;
Это встроенные классы пространства имён Microsoft.AspNetCore.Identity

2024-04-20 17:34 UTC, jacksever commented on api/appsettings.json
> +    "SecretKey": "9c56bbb2442aa20f7d48ce5ba13b75c38000266334fb008387322a8a8ff24944",
Конечно, да. Никаких ключей, паролей и каких-то иных секретов мы не добавляем в Git вообще. Мы храним их в переменных окружения на локальном компе (это может быть даже просто локальный файл, который не индексируется в Git), а также в переменных окружения пайплайнов, если у нас настроен CI/CD

2024-04-20 17:35 UTC, jacksever commented on api/Controllers/AccountController.cs
> +        private readonly SignInManager<AppUser> _signManager;
А, понял! Спасибо!

2024-04-20 19:08 UTC, Andreymlc commented on api/Controllers/StudentController.cs
> +using Microsoft.AspNetCore.Mvc;
Microsoft.EntityFrameworkCore is not used in this file

2024-04-20 21:42 UTC, Andreymlc commented on api/Program.cs
> +    options.DefaultSignInScheme =
A standard authentication scheme is set for all these values

2024-04-30 07:45 UTC, jacksever commented on api/Configuration/StudentConfiguration.cs
> +            builder.Property(s => s.PasswordHash)
Супер! 👍

2024-04-30 07:47 UTC, jacksever commented on api/Controllers/AccountController.cs
> +            var result  = _passwordHasher.VerifyHashedPassword(user, user.PasswordHash, loginDto.Password);
Лучше называть не result, а более четко. Например, здесь у тебя верифицируется пароль и хеш-пароль от пользователя. Можно назвать переменную как `isPasswordHashValid`, допустим. Это название более лучше описывает зачем это переменная нужна. В ином случае под result можно подразумевать всё то, что ты хочешь вернуть в этой функции :)

2024-04-30 07:50 UTC, jacksever commented on api/Controllers/AccountController.cs
> +            if (result != PasswordVerificationResult.Success) return NotFound("Неверное имя пользователя или пароль!");
Под UX мы не пишем восклицательные знания в сообщениях. Ни в возвратных от сервера, ни в клиентских. Это пользователь может расценивать, что на него кричат :)

И ещё одна причина этому - иногда клиенты делают проверку на конкретное сообщение, возвращенное от сервера. И восклицательный знак там точно лишний, так как он может быть, может не быть. И получается, что проверка на клиенте может не пройти. А система должна быть универсальная

2024-04-30 07:53 UTC, jacksever commented on api/Controllers/AccountController.cs
> +        public async Task<IActionResult> Login(LoginDto loginDto)
Нужно ли здесь указывать `[FromBody]`, например?

2024-04-30 07:54 UTC, jacksever commented on api/Controllers/AccountController.cs
> +                    return BadRequest("Such a user already exists!");
Выше сообщения об ошибках на русском, тут на английском :)

2024-04-30 07:55 UTC, jacksever commented on api/Controllers/AccountController.cs
> +                var createUser = await _studentManager.CreateAsync(student);
Наверное пользователь уже создан к тому моменту)

```suggestion
                var createdUser = await _studentManager.CreateAsync(student);
```

2024-04-30 07:56 UTC, jacksever commented on api/Controllers/AccountController.cs
> +}
А ты не хочешь логировать действия, которые совершает сервер? С помощью Logger? Было бы значительно удобнее при дебаге вам

2024-04-30 07:56 UTC, jacksever commented on api/Controllers/AccountController.cs
> +}
FYI @NN171

2024-04-30 07:57 UTC, jacksever commented on api/Migrations/20240429154251_UpdateStudents.cs
> +    public partial class UpdateStudents : Migration
Пустая миграция :)

2024-04-30 07:59 UTC, jacksever commented on api/Service/TokenService.cs
> +public class TokenService : ITokenService{
```suggestion
public class TokenService : ITokenService {
```

2024-04-30 08:01 UTC, jacksever commented on api/Service/TokenService.cs
> +    public TokenService(IConfiguration config){
```suggestion
    public TokenService(IConfiguration config) {
```

В продуктах JetBrains форматировать кода по код-стилю доступно с помощью `Ctrl + Alt + L`. Используй это. Если пишешь в Visual Studio - то погляди какая комбинация клавиш там есть.

Тоже самое касается импортов. В Rider это `Ctrl + Alt + O`. Используй и не допускай лишних импортов в файле

2024-04-30 08:03 UTC, jacksever commented on api/Service/TokenService.cs
> +        var creds = new SigningCredentials(_key,SecurityAlgorithms.HmacSha512Signature);
```suggestion
        var creds = new SigningCredentials(_key, SecurityAlgorithms.HmacSha512Signature);
```

2024-04-30 11:30 UTC, Andreymlc commented on api/Controllers/AccountController.cs
> +            if (result != PasswordVerificationResult.Success) return NotFound("Неверное имя пользователя или пароль!");
"Это пользователь может расценивать, что на него кричат" хахахах, учту

2024-04-30 11:32 UTC, Andreymlc commented on api/Controllers/AccountController.cs
> +                    return BadRequest("Such a user already exists!");
Везде поменяю на английский, на русском старые сообщения

2024-04-30 11:36 UTC, Andreymlc commented on api/Controllers/AccountController.cs
> +                var createUser = await _studentManager.CreateAsync(student);
Ну по сути пользователя мы создаем именно методом CreateAsync

2024-04-30 11:42 UTC, Andreymlc commented on api/Service/TokenService.cs
> +    public TokenService(IConfiguration config){
Я не сделал себе лицензию, поэтому в VS code пишу. Надо действительно посмотреть как форматировать в VS

2024-04-30 12:26 UTC, NN171 commented on api/Service/TokenService.cs
> +    public TokenService(IConfiguration config){
Пока что никак. Есть расширение code formatter, но он только для js

2024-04-30 12:29 UTC, NN171 commented on api/Controllers/AccountController.cs
> +}
То есть, используя интерфейс ILogger? 
![Screenshot_2024-04-30-15-29-34-31_4641ebc0df1485bf6b47ebd018b5ee76.jpg](https://github.com/ImmortalIdiot/RUTLead-Backend/assets/61082311/816ff931-df8b-4f93-8672-399358966b69)

2024-04-30 13:37 UTC, jacksever commented on api/Controllers/AccountController.cs
> +}
Ага. Чем больше логами вы покрываете функции и то, что внутри происходит, тем проще вам будет понимать, как работает программа, что приходит в endpoint, что создано, что нет и какие ошибки возникают. Я могу как-нибудь показать, как обычно логируют в таких случаях, чтобы было удобнее)

2024-04-30 13:37 UTC, jacksever commented on api/Controllers/AccountController.cs
> +                var createUser = await _studentManager.CreateAsync(student);
Так ты в переменную записываешь уже созданного пользователя. Так что, ты его уже создал ранее :)

2024-04-30 13:38 UTC, Andreymlc commented on api/Controllers/AccountController.cs
> +}
Надо разобраться как с этим вообще работать

2024-04-30 13:38 UTC, jacksever commented on api/Controllers/AccountController.cs
> +                var createUser = await _studentManager.CreateAsync(student);
Типа именования корректные в формате:

- `currentTime`
- `createdUser`
- `isValidData`
- `shouldShowToast`

2024-05-05 20:57 UTC, jacksever approved these changes

2024-05-06 18:09 UTC, merged