#16 - Make the data validation
ImmortalIdiot/RUTLead-Backend pull request #30
Opened 2024-05-10 19:48 UTC by Andreymlc

2024-05-11 09:10 UTC, jacksever commented on api/DataAnnotations/PasswordValidation.cs
> +    {
```suggestion
namespace api.DataAnnotations 
{
    public class PasswordValidation : ValidationAttribute
    {
```

2024-05-11 09:11 UTC, jacksever commented on api/DataAnnotations/PasswordValidation.cs
> +        protected override ValidationResult? IsValid(object? password, ValidationContext validationContext)
Почему `password` - это `object?`? Ты же потом все равно приводишь к string и используешь только его. Не кажется, что усложнение? Ведь под password сейчас я смогу подставить всё что угодно, даже число)

2024-05-11 09:13 UTC, jacksever commented on api/DataAnnotations/StudentIdValidation.cs
> +        protected override ValidationResult? IsValid(object? studentId, ValidationContext validationContext)
Такой же вопрос. Это переопределение функции такое обязательное, что там `object`?

2024-05-11 09:14 UTC, jacksever commented on api/DataAnnotations/StudentIdValidation.cs
> +            if (string.IsNullOrWhiteSpace(studentIdString) || studentIdString.Length != 8) return new ValidationResult("The student ID number must be exactly 8 characters long");
Что будет с этой проверкой, если `studentIdString == null`? Ты сможешь вызвать все эти функции без краша? Или вернется `ValidationResult.Success`?

2024-05-11 09:15 UTC, jacksever commented on api/Dto/Account/RegisterDto.cs
> +        [Required, RegularExpression(@"^[А-ЯЁ][а-яё]+(?:\s[А-ЯЁ][а-яё]+){2}$", ErrorMessage = "Invalid username")]
```suggestion
        [Required, RegularExpression(@"^[А-ЯЁ][а-яё]+(?:\s[А-ЯЁ][а-яё]+){2}$", ErrorMessage = "Incorrect username")]
```

Старайся не использовать `Invalid` нигде в видимых сообщениях для пользователя. А то для иностранного сегмента это может звучать грубо :)

2024-05-11 09:15 UTC, jacksever commented on api/Dto/Account/RegisterDto.cs
> +        [Required, RegularExpression(@"^[А-ЯЁ]{3}[а-яё]{0,2}-\d{3}$", ErrorMessage = "Invalid user group")]
```suggestion
        [Required, RegularExpression(@"^[А-ЯЁ]{3}[а-яё]{0,2}-\d{3}$", ErrorMessage = "Incorrect user group")]
```

2024-05-12 18:35 UTC, Andreymlc commented on api/DataAnnotations/StudentIdValidation.cs
> +            if (string.IsNullOrWhiteSpace(studentIdString) || studentIdString.Length != 8) return new ValidationResult("The student ID number must be exactly 8 characters long");
В эту функцию null попасть не может, так как у поля StudentId есть аннотация Required. Я сделал проверку на null, чтобы убрать лишние предупреждения vs code

2024-05-18 22:23 UTC, NN171 requested changes
В остальном, вроде ок

2024-05-18 22:23 UTC, NN171 commented on api/Dto/Account/RegisterDto.cs
> +        [Required, RegularExpression(@"^[А-ЯЁ][а-яё]+(?:\s[А-ЯЁ][а-яё]+){2}$", ErrorMessage = "Incorrect username")]
Тоже сначала думал так сделать, а потом вспомнил, что есть студенты из стран, где используется 4 слова в ФИО (но на двойное имя предлагаю забить)
![image](https://github.com/ImmortalIdiot/RUTLead-Backend/assets/61082311/fdd1db64-220f-4421-bf0b-96b0ee0863c1)

2024-05-19 10:29 UTC, NN171 approved these changes
Кажется, теперь все нормально

2024-05-19 12:15 UTC, merged